baseURL = "http://blog.redrobin.company"
languageCode = "en"
title = "Blog - RedRobin"
theme = "kiss"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.info]
enableSocial = true
codeCopy = true

[params.social]
github = "upils"
rss = "index.xml"

[params.social.config]
platforms = ["github", "rss"]

[permalinks]
posts = "/:year/:month/:title/"